[package]
name = "centaureissi_importer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
maildirs = "0.2.2"
reqwest = { version = "0.12", features = ["json","multipart"] }
tokio = { version = "1", features = ["full"] }
